### ISSUE TITLE
No way to store float, int, or bool

### ISSUE THREAD

**Issue by laposata** [lucascalero/CS4500_A1_part2#4]
As it stands arrays can only store strings and objects, objects cant store any data on their own so there is no way to store any other data type, some other structures are needed, for my group i have array store void* and then have sub class arrays that take in and put out int, float, bools but wahtever you think will work is good with me

**Comment by luzcalero** [comment]
You are totally right!

I just pushed a lot of changes to array.h. You should keep pulling in the next few hours.

I just pushed StrArray and made a lot of changes to Array (for Object). I understand what you were saying about void*, but I would prefer to have a generalized Array that works for Objects (and therefore inherits a lot for String. And have separate Int, float and bool arrays. 

returning void* as a generalization for a so many classes sounded weird, but I can be convinced if you are adamant. :) Thanks for your comments 👍

**Comment by james-herbstritt** [comment]
void pointers are a common approach to generics in c. I think the idea is that this array can store multiple different types, so having separate "StrArray" and different type arrays is not what I think is meant to be aimed for. Returning a void pointer is an acceptable practice (if you look at the man page for malloc it returns a void pointer). Of course though these are all design decisions, so if you are adamant that your arrays be strictly typed in the manner they currently are, I can understand that.

**Comment by laposata** [comment]
As james said above, any choice is acceptable, what matters is the design decision as long as its defendable. As it stands i still do not believe it possible so if this could be added quickly htat would be appreciated

**Comment by luzcalero** [comment]
For sure! I'm currently implementing  spec with void*.

Will push tonight or early tomorrow.

Sorry for the wait!

**Comment by luzcalero** [comment]
I just pushed the most recent changes. 

Is that okay? I'm currently celebrating my anniversary with my partner, but I'm happy to make changes early tomorrow. Sorry for the delay.

**Comment by james-herbstritt** [comment]
I think equals should take an Object* and not a void pointer. We want to be able to store multiple types in the array but not pass anything to the equals method. Also I think because you have defined the different "types" of arrays you no longer need the void*. You're kind of straddling strictly typing the arrays and having them take generics.

**Comment by luzcalero** [comment]
I just changed it!
I tried removing the void* from the Array class and got errors in the subclasses. This is what vs code says when I replace the void* with Object* for get and remove in the Array class:
return type is not identical to nor covariant with return type "Object *" of overridden virtual function "Array::remove"

I get this error for all the primitive implementations of Array (Float,Bool and Int Array)

**Comment by james-herbstritt** [comment]
Did you change the signature of equals in those?

**Comment by luzcalero** [comment]
I think so? What do you mean? Object* are cast to Array* to check for equality. Right?

Either way I added more to the signature.

**Comment by james-herbstritt** [comment]
Yeah, you need to cast to an array.
